elasticsearch:
  image: jritsema/rpi-elasticsearch:2.4.0
  volumes:
    - ./elasticsearch:/data
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - CLUSTER_NAME=my-cluster
    - LISTEN=0.0.0.0
  restart: always

kibana:
  image: jritsema/rpi-kibana:4.6.1
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  restart: always